### ISSUE TITLE
Epic: Club system

### ISSUE THREAD

**Issue by rawat07102** [rawat07102/club-dj-web#3]
## Features
- [ ] Creator can create playlists and host live events.
- [ ] Users can follow clubs to save them for easier access.
- [ ] Users can like playlists.
- [ ] instead of choosing DJs users will request videos to be added to the playlist or to queue of live event, in requested tab.
